<?php
/**
 * Automated Daily Attendance Report via WhatsApp
 * Sends Dasindu's daily attendance to +94783788180
 */

require_once 'database.php';
require_once 'config_whatsapp.php';
require_once 'whatsapp_web_sender.php';

// Configuration
$DASINDU_USER_ID = 141;
$DASINDU_BADGE_ID = '30132';
$TARGET_WHATSAPP = '+94783788180';
$REPORT_DATE = date('Y-m-d'); // Today's date

echo "📱 CIAH Attendance - Automated Daily Report\n";
echo "==========================================\n";
echo "Employee: DASINDU (ID: $DASINDU_USER_ID, Badge: $DASINDU_BADGE_ID)\n";
echo "Target WhatsApp: $TARGET_WHATSAPP\n";
echo "Report Date: $REPORT_DATE\n\n";

try {
    $db = getDB();
    
    // Get Dasindu's user information
    $stmt = $db->prepare("SELECT * FROM users WHERE id = ?");
    $stmt->execute([$DASINDU_USER_ID]);
    $user = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$user) {
        throw new Exception("Dasindu not found in system!");
    }
    
    echo "👤 Employee Details:\n";
    echo "- Official Name: {$user['name']}\n";
    echo "- Calling Name: {$user['calling_name']}\n";
    echo "- Department: {$user['department_name']}\n";
    echo "- Company: {$user['company_name']}\n\n";
    
    // Get today's attendance data
    $nextDate = (new DateTime($REPORT_DATE))->modify('+1 day')->format('Y-m-d');
    
    $stmt = $db->prepare("
        SELECT 
            MIN(CASE WHEN state IN (0, 2, 4) THEN check_time END) as first_checkin,
            MAX(CASE WHEN state IN (1, 3, 5) THEN check_time END) as last_checkout,
            COUNT(*) as total_records
        FROM attendance 
        WHERE user_id = ? AND check_time >= ? AND check_time < ?
    ");
    $stmt->execute([$DASINDU_USER_ID, $REPORT_DATE, $nextDate]);
    $attendance = $stmt->fetch(PDO::FETCH_ASSOC);
    
    // Get all attendance records for detailed view
    $stmt = $db->prepare("
        SELECT check_time, state 
        FROM attendance 
        WHERE user_id = ? AND check_time >= ? AND check_time < ?
        ORDER BY check_time ASC
    ");
    $stmt->execute([$DASINDU_USER_ID, $REPORT_DATE, $nextDate]);
    $records = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Format attendance times
    $firstIn = $attendance['first_checkin'] ? formatAttendanceTime($attendance['first_checkin']) : null;
    $lastOut = $attendance['last_checkout'] ? formatAttendanceTime($attendance['last_checkout']) : null;
    $totalHours = calculateTotalHours($attendance['first_checkin'], $attendance['last_checkout']);
    $status = getAttendanceStatus($attendance['first_checkin'], $attendance['last_checkout']);
    
    // Check if late (assuming 9:00 AM work start)
    $isLate = $attendance['first_checkin'] ? isLateForUserOnDate($db, $DASINDU_USER_ID, $REPORT_DATE, $attendance['first_checkin']) : false;
    
    echo "📊 Today's Attendance Summary:\n";
    echo "- First Check-in: " . ($firstIn ?: 'None') . "\n";
    echo "- Last Check-out: " . ($lastOut ?: 'None') . "\n";
    echo "- Total Hours: $totalHours\n";
    echo "- Status: $status\n";
    echo "- Late: " . ($isLate ? 'Yes' : 'No') . "\n";
    echo "- Total Records: {$attendance['total_records']}\n\n";
    
    // Build WhatsApp message
    $message = "📋 *DAILY ATTENDANCE REPORT*\n";
    $message .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n";
    
    $message .= "👤 *Employee:* {$user['calling_name']} ({$user['name']})\n";
    $message .= "🏷️ *Badge:* $DASINDU_BADGE_ID\n";
    $message .= "🏢 *Department:* {$user['department_name']}\n";
    $message .= "📅 *Date:* " . date('l, F j, Y', strtotime($REPORT_DATE)) . "\n\n";
    
    $message .= "⏰ *ATTENDANCE SUMMARY*\n";
    $message .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
    
    if ($attendance['total_records'] > 0) {
        $message .= "🕐 *First Check-in:* " . ($firstIn ?: 'None') . "\n";
        $message .= "🕐 *Last Check-out:* " . ($lastOut ?: 'None') . "\n";
        $message .= "⏱️ *Total Hours:* $totalHours\n";
        $message .= "📊 *Status:* $status\n";
        $message .= "⚠️ *Late:* " . ($isLate ? 'Yes ⚠️' : 'No ✅') . "\n";
        $message .= "📝 *Records:* {$attendance['total_records']}\n\n";
        
        // Add detailed records if there are multiple
        if (count($records) > 2) {
            $message .= "📝 *DETAILED RECORDS*\n";
            $message .= "━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
            foreach ($records as $record) {
                $time = formatAttendanceTime($record['check_time']);
                $type = ($record['state'] % 2 == 0) ? 'IN' : 'OUT';
                $message .= "$type: $time\n";
            }
            $message .= "\n";
        }
    } else {
        $message .= "❌ *NO ATTENDANCE RECORDED*\n";
        $message .= "Employee did not check in today.\n\n";
    }
    
    $message .= "🤖 *Generated by CIAH Attendance System*\n";
    $message .= "⏰ *Report Time:* " . date('H:i:s') . "\n";
    $message .= "📱 *Sent from:* " . WHATSAPP_SENDER_NUMBER . "\n\n";
    
    $message .= "_This is an automated daily report._";
    
    echo "📱 Sending WhatsApp message...\n";
    echo "Message length: " . strlen($message) . " characters\n\n";
    
    // Send the message
    $result = sendWhatsAppMessage($TARGET_WHATSAPP, $message);
    
    if ($result) {
        echo "✅ SUCCESS: Daily report sent successfully!\n";
        
        // Log the notification
        $stmt = $db->prepare("INSERT INTO notifications (user_id, type, channel, subject, message, status) VALUES (?, ?, ?, ?, ?, ?)");
        $stmt->execute([
            $DASINDU_USER_ID,
            'daily_report',
            'whatsapp',
            "Daily Attendance Report - $REPORT_DATE",
            $message,
            'sent'
        ]);
        
        echo "📝 Notification logged to database.\n";
    } else {
        echo "❌ FAILED: Could not send daily report.\n";
    }
    
} catch (Exception $e) {
    echo "❌ ERROR: " . $e->getMessage() . "\n";
}

echo "\n" . str_repeat("=", 50) . "\n";
echo "📊 Daily report process completed.\n";
echo "⏰ Execution time: " . date('Y-m-d H:i:s') . "\n";
?>