<?php
require_once __DIR__ . '/auth.php';
if (currentUser()) { header('Location: index.php'); exit; }
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (loginUser($_POST['username'] ?? '', $_POST['password'] ?? '')) { header('Location: index.php'); exit; }
    $error = 'Invalid username or password.';
}
?><!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"><title>Sign in - <?php echo htmlspecialchars(COMPANY_NAME); ?></title><meta name="theme-color" content="#102a34"><link rel="manifest" href="manifest.json"><link rel="apple-touch-icon" href="assets/icons/apple-touch-icon.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="stylesheet" href="assets/style.css"><style>
.login-shell{min-height:100vh;display:grid;grid-template-columns:minmax(320px,46%) 1fr;background:#102a34;color:#fff}.login-panel{display:flex;align-items:center;justify-content:center;padding:clamp(28px,7vw,88px);background:#f4f8f7}.login-form{width:min(420px,100%);color:#122334}.login-kicker{font-size:11px;font-weight:800;letter-spacing:1.8px;color:#168e7b}.login-form h1{font-size:38px;line-height:1.05;margin:14px 0 10px}.login-form p{color:#68777d;margin-bottom:30px}.login-label{display:block;font-size:12px;font-weight:700;margin:17px 0 7px}.login-input{width:100%;padding:14px 15px;border:1px solid #d7e2e0;border-radius:7px;background:#fff;box-shadow:0 1px 2px rgba(18,42,52,.04);font:inherit}.login-input:focus{outline:3px solid rgba(47,178,143,.2);border-color:#2fb28f}.login-submit{width:100%;margin-top:25px;padding:14px;border:0;border-radius:7px;background:#137d72;color:#fff;font-weight:800;cursor:pointer}.login-error{color:#a73e31;background:#fff0ed;border:1px solid #f3cfc8;padding:11px 13px;border-radius:7px;margin-bottom:16px}.login-showcase{position:relative;overflow:hidden;padding:clamp(30px,6vw,90px);display:flex;align-items:flex-end;background:linear-gradient(145deg,#123b45 0%,#0e2936 62%,#164f54 100%)}.login-showcase:after{content:'';position:absolute;width:360px;height:360px;border:1px solid rgba(116,222,190,.25);border-radius:50%;right:-100px;top:-100px;box-shadow:0 0 0 38px rgba(116,222,190,.04),0 0 0 76px rgba(116,222,190,.03)}.login-showcase-content{position:relative;z-index:1;max-width:540px}.login-mark{width:58px;height:58px;display:grid;place-items:center;border-radius:12px;background:#2fb28f;color:#092f37;font-size:25px;font-weight:900;margin-bottom:28px}.login-showcase h2{font-size:clamp(30px,4vw,54px);line-height:1.02;margin:0 0 20px}.login-showcase p{font-size:17px;line-height:1.7;color:#b9d3d0;max-width:470px}.login-meta{display:flex;gap:10px;flex-wrap:wrap;margin-top:35px}.login-meta span{font-size:12px;color:#d7ebe7;border:1px solid rgba(215,235,231,.25);padding:7px 14px;border-radius:50px}.login-showcase:before{content:'';position:absolute;top:0;left:0;right:0;bottom:0;background:radial-gradient(circle at 20% 80%,rgba(47,178,143,.18),transparent 60%)}
@media (max-width:820px){.login-shell{grid-template-columns:1fr}.login-panel{min-height:auto;padding:clamp(32px,9vw,56px) 24px;order:2}.login-form h1{font-size:32px}.login-showcase{min-height:auto;padding:38px 24px;align-items:flex-start}.login-showcase:before{background:radial-gradient(circle at 85% 20%,rgba(47,178,143,.25),transparent 55%)}.login-meta{margin-top:22px}}
</style>
<script>if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('sw.js').catch(function(){})});}</script>
</head>
<body><main class="login-shell"><section class="login-panel"><form method="post" class="login-form"><h1>Welcome</h1><p>Sign in to manage attendance, leave, overtime, and rosters.</p>
<?php if ($error): ?><div class="login-error"><?php echo htmlspecialchars($error); ?></div><?php endif; ?>
<label class="login-label" for="username">Username</label><input class="login-input" id="username" name="username" required autofocus autocomplete="username"><label class="login-label" for="password">Password</label><input class="login-input" id="password" type="password" name="password" required autocomplete="current-password"><button class="login-submit" type="submit">Sign in securely</button>
</form></section><section class="login-showcase"><div class="login-showcase-content"><div class="login-mark"><img src="assets/logo.jpg" alt="Logo" style="width:58px;height:58px;border-radius:12px;object-fit:contain;background:#fff;padding:4px;"></div><h2>HRIS ROWELMARK GROUP</h2><p>One connected workspace for reliable device sync, approvals, department oversight, and decision-ready reporting.</p><div class="login-meta"><span>Live device sync</span><span>Role-based access</span><span>Management reports</span></div></div></section></main></body></html>
